### PR TITLE
JavaScript standard compilant refactor

### PR DESCRIPTION
**Pull request by soyilai**
ban yourself from using JS again, please

you're not worthy of being on this house

### CODE REVIEW

**Comment by soyilai** [comment]
had to check if i commited the right thing lmao

**Comment by rivest-oss** [comment]
:eyes:

**Comment by rivest-oss** [comment]
It doesn't works properly. Test it with the `ejemplos.bir` file.

**Comment by soyilai** [comment]
> It doesn't works properly. Test it with the `ejemplos.bir` file.

with all due respect, fucc u /jk

**Pull request merged**
